
WHITESPACE = _{ " " | "\n" | "\t" | "," }

rparen = _{ "(" }
lparen = _{ ")" }

nil = {
    ""
}

atom = _{
    identifier
}

identifier = @{
      (ASCII_ALPHA | "_" | "-" )+
    | ("." | "<" | ">" | "$" | "@" | "_" | "!" | "=" | "?" | ":")+
}

quote_exp = ${
    "'" ~ exp
}

exp = _{
    atom | paren_list
}

list = !{
    (exp | quote_exp) ~ (list | nil)
}

paren_list = _{
      rparen ~ (list | nil) ~ lparen
}

silent_eoi = _{
    !ANY
}

program = _{
    SOI ~ exp ~ silent_eoi
}
