
WHITESPACE = _{ " " | "\n" | "\t" | "," }

rparen = _{ "(" }
lparen = _{ ")" }

nil = {
    ""
}

atom = _{
    identifier
}

identifier = @{
      (ASCII_ALPHA | "_" | "-" )+
    | ("." | "<" | ">" | "$" | "@" | "_" | "!" | "=" | "'")+
}

exp = _{
    atom | list
}

seq = {
    exp ~ (seq | nil)
}

list = _{
      rparen ~ (seq | nil) ~ lparen
}

silent_eoi = _{
    !ANY
}

program = _{
    SOI ~ list ~ silent_eoi
}
